# ===============================
# Application
# ===============================
spring.application.name=api-gateway
spring.main.web-application-type=reactive
server.port=6666

# ===============================
# HTTPS / SSL CONFIG (Gateway)
# ===============================
server.ssl.enabled=true
server.ssl.key-store=classpath:ssl/api-gateway-keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-store-password=akshay
server.ssl.key-alias=api-gateway


# ===============================
# Eureka
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# ===============================
# Spring Cloud Gateway
# ===============================
# Enable Eureka-based dynamic routing
spring.cloud.gateway.discovery.locator.enabled=true

# Use lowercase service IDs in routes
spring.cloud.gateway.discovery.locator.lower-case-service-id=true


# ===============================
# Order Service Route
# ===============================
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://ORDER-SERVICE

# Route all order-related APIs
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/orders/**

# Forward path as-is to order service
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/api/orders/(?<segment>.*), /api/orders/${segment}

# ===============================
# Payment Service Route
# ===============================
spring.cloud.gateway.routes[1].id=payment-service
spring.cloud.gateway.routes[1].uri=lb://PAYMENT-SERVICE

# Route all payment-related APIs
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/payments/order/{id}
spring.cloud.gateway.routes[1].predicates[1]=Method=GET

# Forward path as-is to payment service
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/api/payments/order/(?<segment>.*), /api/payments/order/${segment}

# ===============================
# Logging (dev only)
# ===============================
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.reactor.netty.http.client=DEBUG
