spring.application.name=payment-service

server.port = 2020

# ===============================
# Eureka Server Registration
# ===============================

eureka.client.service-url.defaultZone: http://localhost:8761/eureka/

# ===============================
# Resilience4j - Circuit Breaker
# ===============================

resilience4j.circuitbreaker.instances.orderService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.orderService.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.orderService.sliding-window-size=10
resilience4j.circuitbreaker.instances.orderService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.orderService.permitted-number-of-calls-in-half-open-state=3

# ===============================
# Resilience4j - Retry
# ===============================

resilience4j.retry.instances.orderService.max-attempts=3
resilience4j.retry.instances.orderService.wait-duration=2s

# Resilience4j core logs
logging.level.io.github.resilience4j=DEBUG

# CircuitBreaker state transitions
logging.level.io.github.resilience4j.circuitbreaker=DEBUG

# Retry attempts
logging.level.io.github.resilience4j.retry=DEBUG

# Spring AOP (to confirm proxying)
logging.level.org.springframework.aop=DEBUG

# Trust producer certificate
#ssl.key-store=classpath:ssl/order-service-keystore.p12
#ssl.key-store-password=akshay
#ssl.trust-store=classpath:ssl/consumer-truststore.jks
#ssl.trust-store-password=akshay
ssl.trust-store=classpath:ssl/consumer-truststore.jks
ssl.trust-store-password=akshay


